### ISSUE TITLE
Embedded tor suite was not installed on Windows 10 x64

### ISSUE THREAD

**Issue by trszdev** [bookchin/granax#11]
after ```npm i --save granax``` i got node_modules/granax/bin consisting of following files:

- .gitkeep
- .tbb.exe

which leads to this error:
```
{ Error: spawn C:\Users\Emil\Desktop\https\node_modules\granax\bin\Browser\TorBrowser\Tor\tor.exe ENOENT
    at _errnoException (util.js:1019:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn C:\\Users\\Emil\\Desktop\\https\\node_modules\\granax\\bin\\Browser\\TorBrowser\\Tor\\tor.exe',
  path: 'C:\\Users\\Emil\\Desktop\\https\\node_modules\\granax\\bin\\Browser\\TorBrowser\\Tor\\tor.exe',
  spawnargs:
   [ '-f',
     'C:\\Users\\Emil\\AppData\\Local\\Temp\\granax-0ddd5944050d0de7' ] }
```

So, I suggest you adding these features:

- GRANAX_USE_SYSTEM_TOR for every system
- torPath option for TorController (or something like that)
- testing ```download-tbb.js``` script

**Comment by bookchin** [comment]
> GRANAX_USE_SYSTEM_TOR for every system

Not feasible on windows (to my knowledge), since we have no way of reliably detecting where the user might have tor installed (whereas on linux and osx we can use `which`). 

> torPath option for TorController (or something like that)

I can see this being useful and will be happy to add that (or accept a PR that adds it).

> testing download-tbb.js script

Yeah, this is almost certainly what failed for you, the download failed and wrote the result to `.tbb.exe` (see what that it - is it a webpage with a 404 or anything?).

**Comment by bookchin** [comment]
At minimum, I think the following need to happen:

* If downloading tbb on postinstall returns anything but 200, fail hard and give user an error message
* Allow overriding the path to tor with wither an environment variable or option

**Comment by trszdev** [comment]
> Not feasible on windows (to my knowledge), since we have no way of reliably detecting where the user might have tor installed (whereas on linux and osx we can use which).

``` where tor ``` in win cmd, https://ss64.com/nt/where.html

> I can see this being useful and will be happy to add that (or accept a PR that adds it).

will probably help you :)
